# Generated by Django 5.2.17 on 2026-08-09 06:41

import ckeditor_uploader.fields
import django.db.models.deletion
import django.utils.timezone
import utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability_name', models.CharField(max_length=100, verbose_name='نوع توانمندی ')),
                ('slug', models.SlugField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'توانمندی',
                'verbose_name_plural': 'توانمندی ها',
            },
        ),
        migrations.CreateModel(
            name='FieldWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldwork_name', models.CharField(max_length=100, verbose_name='زمینه فعالیت  ')),
                ('slug', models.SlugField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'زمینه',
            },
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_name', models.CharField(max_length=100, verbose_name='حقیقی/حقوقی ')),
                ('slug', models.SlugField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'شخص',
                'verbose_name_plural': 'اشخاص',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100, verbose_name='نوع خدمات  ')),
                ('slug', models.SlugField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'خدمات',
                'verbose_name_plural': 'زمینه فالیت ها  ',
            },
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summery_description', models.TextField(blank=True, default='', null=True, verbose_name=' توضیحات کوتاه')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=None)),
                ('image_name', models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name=' تصویر  متخصص')),
                ('ostan', models.CharField(max_length=50, verbose_name='استان')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='وضعیت فعال /غیر فعال')),
                ('subscription', models.BooleanField(blank=True, default=True, verbose_name='اشتراک فعال /غیر فعال')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درج')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='آخرین بروز رسانی متخصص')),
                ('degree', models.CharField(max_length=50, verbose_name='آخرین مدرک تحصیلی')),
                ('slug', models.SlugField(max_length=200, null=True)),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ability', to='specialties.ability', verbose_name='نوع توانمندی')),
                ('expert_customuser', models.ForeignKey(blank=None, max_length=11, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='شماره موبایل ')),
                ('expert_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experts_user', to='accounts.customer', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'متخصص',
                'verbose_name_plural': 'متخصص ها',
            },
        ),
        migrations.CreateModel(
            name='ExpertGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name=' تصویر  متخصص')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_product', to='specialties.expert', verbose_name='متخصص')),
            ],
            options={
                'verbose_name': 'تصویر ',
                'verbose_name_plural': 'تصاویر',
            },
        ),
        migrations.CreateModel(
            name='ExpertiseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_title', models.CharField(max_length=500, verbose_name='عناوین تخصص')),
                ('image_name', models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name=' تصویر گروه تخصص')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='وضعیت فعال /غیر فعال')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درج')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='آخرین بروز رسانی تخصص')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('group_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups_parent', to='specialties.expertisegroup', verbose_name='والد گروه تخصص')),
            ],
            options={
                'verbose_name': 'گروه تخصص',
                'verbose_name_plural': ' گروه تخصص ها',
            },
        ),
        migrations.AddField(
            model_name='expert',
            name='expertise_group',
            field=models.ManyToManyField(related_name='expertises_of_group', to='specialties.expertisegroup', verbose_name='گروه متخصص'),
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=100, verbose_name='نام ویژگی تخصص')),
                ('expert_group', models.ManyToManyField(related_name='Features_of_groups', to='specialties.expertisegroup', verbose_name='گروه تخصص')),
            ],
            options={
                'verbose_name': ' ویژگی تخصص',
                'verbose_name_plural': ' انواع عملگرها تخصص',
            },
        ),
        migrations.CreateModel(
            name='FeatureExpertValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_title', models.CharField(max_length=50, verbose_name=' جنس ویژگی تخصص')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_value', to='specialties.feature', verbose_name='نام ویژگی تخصص')),
            ],
            options={
                'verbose_name': 'نوع تخصص ',
                'verbose_name_plural': 'ماهیت های ویژگی تخصص   ',
            },
        ),
        migrations.CreateModel(
            name='ExpertFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='نوع  ویژکی تخصص')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Expert_features', to='specialties.expert', verbose_name=' نام تخصص ')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialties.feature', verbose_name='نام ویژگی تخصص')),
                ('filter_value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='specialties.featureexpertvalue', verbose_name='مقدار ویژگی برای فیلتر')),
            ],
            options={
                'verbose_name': 'ویژکی تخصص',
                'verbose_name_plural': 'ویژگی های تخصص ها',
            },
        ),
        migrations.AddField(
            model_name='expert',
            name='fieldwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fieldwork', to='specialties.fieldwork', verbose_name='   زمینه کاری'),
        ),
        migrations.AddField(
            model_name='expert',
            name='identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity', to='specialties.identity', verbose_name='نوع اشخاص'),
        ),
        migrations.AddField(
            model_name='expert',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='specialties.services', verbose_name='      نوع خدمات'),
        ),
    ]
