# Generated by Django 5.2.17 on 2026-08-09 06:56

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='image_name',
            field=models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name=' تصویر  متخصص'),
        ),
        migrations.AlterField(
            model_name='expertgallery',
            name='image_name',
            field=models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name=' تصویر  متخصص'),
        ),
        migrations.AlterField(
            model_name='expertisegroup',
            name='image_name',
            field=models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name=' تصویر گروه تخصص'),
        ),
    ]
