# Generated by Django 5.0.6 on 2026-07-20 08:28

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialties', '0005_alter_expert_image_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='image_name',
            field=models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name=' تصویر  متخصص'),
        ),
        migrations.AlterField(
            model_name='expertgallery',
            name='image_name',
            field=models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name=' تصویر  متخصص'),
        ),
        migrations.AlterField(
            model_name='expertisegroup',
            name='image_name',
            field=models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name=' تصویر گروه تخصص'),
        ),
    ]
