# Generated by Django 5.0.6 on 2026-06-13 16:15

import ckeditor_uploader.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='نام')),
                ('family', models.CharField(max_length=30, verbose_name='نام خانوادگی')),
                ('slug', models.SlugField(max_length=30)),
                ('age', models.IntegerField(default=30, verbose_name='سن')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('register_data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ')),
                ('email', models.EmailField(max_length=100, verbose_name='ایمیل')),
                ('image_name', models.CharField(blank=True, default='nophpont.png', max_length=200, null=True, verbose_name='تصویر')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان مقاله ')),
                ('summery_description', models.TextField(blank=True, default='', null=True, verbose_name=' متن مقاله ')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=None, verbose_name=' توضیحات بیشتر درباره مقاله ')),
                ('is_active', models.BooleanField(verbose_name='فعال /غیرفعال')),
                ('main_image', models.ImageField(upload_to='images/blogimg', verbose_name='تصویر اصلی مقاله ')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='blog.author', verbose_name='نویسنده')),
            ],
        ),
    ]
