# Generated by Django 5.2.17 on 2026-09-07 13:59

import ckeditor_uploader.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='کلمه کلیدی که می\u200cخواهید مقاله برای آن رتبه بگیرد', max_length=100, verbose_name='کلمه کلیدی اصلی'),
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_description',
            field=models.CharField(blank=True, help_text='خلاصه\u200cای جذاب از مقاله برای نمایش در نتایج گوگل', max_length=160, verbose_name='توضیحات متا (حداکثر 160 کاراکتر)'),
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='با کاما جدا کنید: آموزش، جنگو، سئو', max_length=255, verbose_name='کلمات کلیدی'),
        ),
        migrations.AddField(
            model_name='blog',
            name='register_data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت'),
        ),
        migrations.AddField(
            model_name='blog',
            name='seo_title',
            field=models.CharField(blank=True, help_text='اگر خالی باشد، عنوان اصلی استفاده می\u200cشود', max_length=70, verbose_name='عنوان سئو (حداکثر 70 کاراکتر)'),
        ),
        migrations.AlterField(
            model_name='author',
            name='register_data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='توضیحات کامل مقاله'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال/غیرفعال'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='main_image',
            field=models.ImageField(upload_to='images/blogimg/', verbose_name='تصویر اصلی مقاله'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='summery_description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='خلاصه مقاله'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=50, verbose_name='عنوان مقاله'),
        ),
    ]
