# Generated by Django 5.2.17 on 2026-08-09 06:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('specialties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(max_length=200, verbose_name='متن نظر')),
                ('registerdate', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درج')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت نظر')),
                ('approving_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approving_user2', to=settings.AUTH_USER_MODEL, verbose_name='کاربر تایید کننده نظر')),
                ('comment_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_child', to='comment_scoring_favorites.comment', verbose_name='والد نظر')),
                ('commenting_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approving_user1', to=settings.AUTH_USER_MODEL, verbose_name='کاربر نظر دهنده')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_product', to='products.product', verbose_name='کالا')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
            },
        ),
        migrations.CreateModel(
            name='CommentExpert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(max_length=200, verbose_name='متن نظر')),
                ('registerdate', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درج')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت نظر')),
                ('approving_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approving_user4', to=settings.AUTH_USER_MODEL, verbose_name='کاربر تایید کننده نظر')),
                ('comment_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_child', to='comment_scoring_favorites.commentexpert', verbose_name='والد نظر')),
                ('commenting_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approving_user3', to=settings.AUTH_USER_MODEL, verbose_name='کاربر نظر دهنده')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_expert', to='specialties.expert', verbose_name='متخصص')),
            ],
            options={
                'verbose_name': 'نظرمتخصص',
                'verbose_name_plural': 'نظرات متخصصین',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registerdate', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درج')),
                ('favorite_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_user1', to=settings.AUTH_USER_MODEL, verbose_name='کاربر علاقه مند ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_product', to='products.product', verbose_name='کالا')),
            ],
            options={
                'verbose_name': 'علاقه',
                'verbose_name_plural': 'علایق',
            },
        ),
        migrations.CreateModel(
            name='Scoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registerdate', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درج')),
                ('score', models.PositiveIntegerField(validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_product', to='products.product', verbose_name='کالا')),
                ('scoring_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_user1', to=settings.AUTH_USER_MODEL, verbose_name='کاربر امتیاز دهنده')),
            ],
            options={
                'verbose_name': 'امتیاز',
                'verbose_name_plural': 'امتیازات',
            },
        ),
        migrations.CreateModel(
            name='ScoringExpert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registerdate', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درج')),
                ('score_exp', models.PositiveIntegerField(validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_expert', to='specialties.expert', verbose_name='کالا')),
                ('scoring_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_user', to=settings.AUTH_USER_MODEL, verbose_name='کاربر امتیاز دهنده')),
            ],
            options={
                'verbose_name': 'امتیاز',
                'verbose_name_plural': 'امتیازات',
            },
        ),
    ]
