# Generated by Django 5.2.17 on 2026-08-09 06:41

import datetime
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان تبلیغ')),
                ('description', models.TextField(verbose_name='توضیحات تبلیغ')),
                ('image_name', models.ImageField(help_text='تصویر با کیفیت و مرتبط با تبلیغ', upload_to=utils.FileUpload.upload_to, verbose_name='تصویر تبلیغات')),
                ('url', models.URLField(verbose_name='لینک')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('views_count', models.IntegerField(default=0, verbose_name='تعداد بازدید')),
                ('order', models.IntegerField(default=0, help_text='عدد کمتر = نمایش بالاتر', verbose_name='ترتیب نمایش')),
                ('expiry_date', models.DateTimeField(default=datetime.datetime(2026, 9, 8, 6, 41, 8, 255893, tzinfo=datetime.timezone.utc), help_text='تاریخ و زمانی که تبلیغ منقضی می\u200cشود', verbose_name='تاریخ انقضا')),
            ],
            options={
                'verbose_name': 'تبلیغ',
                'verbose_name_plural': 'تبلیغات',
                'ordering': ['-is_active', 'order', '-created_at'],
            },
        ),
    ]
