# Generated by Django 5.0.6 on 2026-06-13 16:15

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان تبلیغ')),
                ('description', models.TextField(verbose_name='توضیحات تبلیغ')),
                ('image_name', models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name=' تصویر   تبلیغات')),
                ('url', models.URLField(verbose_name='لینک ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
