# Generated by Django 5.2.17 on 2026-08-09 06:56

import datetime
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 8, 6, 56, 4, 986875, tzinfo=datetime.timezone.utc), help_text='تاریخ و زمانی که تبلیغ منقضی می\u200cشود', verbose_name='تاریخ انقضا'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='image_name',
            field=models.ImageField(help_text='تصویر با کیفیت و مرتبط با تبلیغ', upload_to=utils.FileUpload.upload_to, verbose_name='تصویر تبلیغات'),
        ),
    ]
