# Generated by Django 5.0.6 on 2026-06-13 16:22

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image_name',
            field=models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name=' تصویر   تبلیغات'),
        ),
    ]
