# Generated by Django 5.0.6 on 2026-07-19 20:21

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0005_alter_advertisement_image_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ['-is_active', 'order', '-created_at'], 'verbose_name': 'تبلیغ', 'verbose_name_plural': 'تبلیغات'},
        ),
        migrations.AddField(
            model_name='advertisement',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='order',
            field=models.IntegerField(default=0, help_text='عدد کمتر = نمایش بالاتر', verbose_name='ترتیب نمایش'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='views_count',
            field=models.IntegerField(default=0, verbose_name='تعداد بازدید'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='image_name',
            field=models.ImageField(help_text='تصویر با کیفیت و مرتبط با تبلیغ', upload_to=utils.FileUpload.upload_to, verbose_name='تصویر تبلیغات'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='url',
            field=models.URLField(verbose_name='لینک'),
        ),
    ]
