# Generated by Django 5.0.6 on 2026-08-06 15:19

import datetime
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0007_advertisement_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 5, 15, 19, 27, 55326, tzinfo=datetime.timezone.utc), help_text='تاریخ و زمانی که تبلیغ منقضی می\u200cشود', verbose_name='تاریخ انقضا'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='image_name',
            field=models.ImageField(help_text='تصویر با کیفیت و مرتبط با تبلیغ', upload_to=utils.FileUpload.upload_to, verbose_name='تصویر تبلیغات'),
        ),
    ]
