# Generated by Django 5.2.17 on 2026-08-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام کامل')),
                ('role', models.CharField(max_length=100, verbose_name='سمت')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='بیوگرافی')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن')),
                ('credentials', models.TextField(blank=True, null=True, verbose_name='مدارک و گواهی\u200cها')),
                ('skills', models.TextField(blank=True, null=True, verbose_name='مهارت\u200cها')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/', verbose_name='عکس')),
                ('experience_years', models.IntegerField(default=0, verbose_name='سال\u200cهای تجربه')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_featured', models.BooleanField(default=False, verbose_name='نمایش ویژه (کارت بزرگ)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order', 'name'],
            },
        ),
    ]
