# Generated by Django 5.0.6 on 2026-08-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='credentials',
            field=models.TextField(blank=True, null=True, verbose_name='مدارک و گواهی\u200cها'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='skills',
            field=models.TextField(blank=True, null=True, verbose_name='مهارت\u200cها'),
        ),
    ]
