# Generated by Django 5.0.6 on 2026-06-13 16:15

import ckeditor_uploader.fields
import django.db.models.deletion
import django.utils.timezone
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('specialties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='نام')),
                ('title', models.CharField(max_length=30, verbose_name='موضوع  ')),
                ('descriptions', models.TextField(max_length=3000, verbose_name='نظرات  ')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال/غیرفعال')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_title1', models.CharField(blank=True, max_length=500, null=True, verbose_name='متن اول')),
                ('slider_title2', models.CharField(blank=True, max_length=500, null=True, verbose_name='متن دوم')),
                ('slider_title3', models.CharField(blank=True, max_length=500, null=True, verbose_name='متن سوم')),
                ('image_title', models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='تصویر اسلاید')),
                ('slider_link', models.URLField(blank=True, null=True, verbose_name='لینک')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='فعال/غیرفعال')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درج')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
            ],
            options={
                'verbose_name': 'اسلاید',
                'verbose_name_plural': 'اسلایدها',
            },
        ),
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(max_length=200, verbose_name=' عنوان متن')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=None)),
                ('image_title', models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='تصویر اسلاید')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='فعال/غیرفعال')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درج')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('expert', models.ManyToManyField(related_name='about_us_experts', to='specialties.expert', verbose_name='متخصصین')),
                ('user_registered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_us_Customuser', to='accounts.customer', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'درباره ما',
                'verbose_name_plural': 'درباره ماها',
            },
        ),
    ]
