# Generated by Django 5.0.6 on 2026-06-13 16:22

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='image_title',
            field=models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='تصویر اسلاید'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image_title',
            field=models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='تصویر اسلاید'),
        ),
    ]
