# Generated by Django 5.2.17 on 2026-09-08 16:54

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_aboutus_image_title_alter_slider_image_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='image_title',
            field=models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='تصویر اسلاید'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image_title',
            field=models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='تصویر اسلاید'),
        ),
    ]
