# Generated by Django 5.0.6 on 2026-06-13 16:15

import ckeditor_uploader.fields
import django.db.models.deletion
import django.utils.timezone
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100, verbose_name='نام املاکی ')),
                ('image_name', models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name=' تصویر برند فایل')),
                ('slug', models.SlugField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'املاک',
                'verbose_name_plural': ' املاک ها',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=100, verbose_name=' نام ویژگی')),
            ],
            options={
                'verbose_name': 'ویژگی',
                'verbose_name_plural': 'ویژگی ها',
            },
        ),
        migrations.CreateModel(
            name='FeatureValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_title', models.CharField(max_length=50, verbose_name='مقدار ویژگی')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_value', to='realestate.feature', verbose_name='ویژگی')),
            ],
            options={
                'verbose_name': 'مقدار ویژگی ',
                'verbose_name_plural': 'مقدار های ویژگی  ',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=500, verbose_name='نام املاکی')),
                ('summery_description', models.TextField(blank=True, default='', null=True, verbose_name=' توضیحات کوتاه')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('image_name', models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name=' تصویر املاکی')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='قیمت املاکی')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='وضعیت فعال /غیر فعال')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درج')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='آخرین بروز رسانیاملاکی')),
                ('slug', models.SlugField(max_length=200, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=200)),
                ('seo_description', models.TextField(blank=True, max_length=300)),
                ('seo_keywords', models.TextField(blank=True, max_length=400)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='realestate.brand', verbose_name='برنداملاکی')),
            ],
            options={
                'verbose_name': 'املاکی',
                'verbose_name_plural': 'املاکیها',
            },
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='مقدار ویژکی املاکی')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestate.feature', verbose_name='ویژگی ')),
                ('filter_value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='realestate.featurevalue', verbose_name='مقدار ویژگی برای فیلتر')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_features', to='realestate.product', verbose_name='املاکی ')),
            ],
            options={
                'verbose_name': 'ویژکی محصول',
                'verbose_name_plural': 'ویژگی های محصولات',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.ManyToManyField(through='realestate.ProductFeature', to='realestate.feature'),
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name=' تصویر املاکی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_product', to='realestate.product', verbose_name='املاکی ')),
            ],
            options={
                'verbose_name': 'تصویر ',
                'verbose_name_plural': 'تصاویر',
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_title', models.CharField(max_length=500, verbose_name='عناوین املاکی ')),
                ('image_name', models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name=' تصویر گروهاملاکی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='وضعیت فعال /غیر فعال')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درج')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='آخرین بروز رسانیاملاکی')),
                ('slug', models.SlugField(max_length=200, null=True)),
                ('group_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='realestate.productgroup', verbose_name='والد گروهاملاکی')),
            ],
            options={
                'verbose_name': 'گروه املاکی',
                'verbose_name_plural': ' گروه های املاکی ',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_group',
            field=models.ManyToManyField(related_name='products_of_groups', to='realestate.productgroup', verbose_name='گروه املاکی'),
        ),
        migrations.AddField(
            model_name='feature',
            name='product_group',
            field=models.ManyToManyField(related_name='features_of_groups', to='realestate.productgroup', verbose_name='گروه املاکی'),
        ),
    ]
